
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "application-generator.fullname" . }}-auth
  labels:
    {{- include "application-generator.labels" . | nindent 4 }}
type: Opaque
stringData:
  nextAuthSecret: {{ .Values.auth.nextAuthSecret | quote }}
  githubId: {{ .Values.auth.github.id | quote }}
  githubSecret: {{ .Values.auth.github.secret | quote }}
  gitlabId: {{ .Values.auth.gitlab.id | quote }}
  gitlabSecret: {{ .Values.auth.gitlab.secret | quote }}
